#### Q. How to import python libraries?

In [4]:
import numpy as np
import pandas as pd
import matplotlib_inline as plt
import seaborn as sns

#### Q. Identity function: If there are two variables defined as 'a = 3' and 'b = 4', will ID() function return the same values for a and b?
The id() function in python returns the identity of an object, which is actually the memory address. Since, this identity is unique and constant for every object, it will not return same values for a and b.

In [11]:
a="z"
b=3

In [12]:
id(a)

1495312254832

In [10]:
id(b)

1495302891888

#### Q.  How can you change the index of a dataframe in python?

In [ ]:
#Syntax:
DataFrame.set_index(keys, drop=True, append=False, inplace=False, verify_integrity=False) 

#### Q. How to import multiple excel sheets in a data frame?

In [ ]:
#Syntax:
df = pd.concat(pd.read_excel('sheet_name', sheet_name=None), ignore_index=True)

#### Q. write a function using python to impute outliers?

In [ ]:
import numpy as np 
def remove Outliers(x, outlierConstant): 
    a = np.array(x) 
    upper_quartile = np.percentile(a, 75) 
    lower_quartile = np.percentile(a, 25) 
    IQR = (upper_quartile - lower_quartile) * outlierConstant quartileSet = (lower_quartile - IQR, upper_quartile + IQR) 
    
resultList = 
    for y in a.tolist(): 
        if y > = quartileSet[0] and y < = quartileSet[1]: 
            resultList.append(y) 
            return resultList

#### Q. check if the number is an Armstrong number or not

In [ ]:
# take input from the user  
num = int(input("Enter a number: ")) 

# initialize sum 
sum = 0 

# find the sum of the cube of each digit 
temp = num 
while temp > 0: 
    digit = temp % 10 
    sum += digit ** 3 temp //= 10 

# display the result 
if num == sum: 
    print(num,"is an Armstrong number") 
else: print(num,"is not an Armstrong number")

#### Q. What is the apply function in Python? How does it work?
Pandas.apply allow the users to pass a function and apply it on every single value of the Pandas series. 

In [ ]:
#Syntax: 
s.apply(func, convert_dtype=True, args=())

#### Q. How does the reverse function work in Python?
The built-in reverse( ) function reverses the contents of a list object inplace. That means, it does not return a new instance of the original list, rather it makes a direct change to the original list object. 

In [ ]:
#Syntax: 
list.reverse()

#### Q. How do you get the frequency of a categorical column of a dataframe using python?
Using df.value_counts(), where df is the dataframe. The value_counts( ) function returns the counts of the distinct elements in a dataframe column, sorted in descending order by default.

In [ ]:
#Syntax:
df.value_counts()

#### Q. How to drop a column in python?
Pandas 'drop()' method is used to remove specific rows and columns. To drop a column, the parameter 'axis' should be set as 'axis = 1'. This parameter determines whether to drop labels from the columns or rows (index). Default behaviour is, axis = 0.

In [ ]:
#Syntax: 
df2 = df.drop('column_name', axis=1)

#or

df.drop('column_name', axis=1, inplace=True)

#### Q. How to convert a python series object into a dataframe?
The to_frame() is a function that helps us to convert a series object into a dataframe. Syntax: Series.to_frame(name=None) name: this name will substitute the existing series name while creating the dataframe.

In [ ]:
#Syntax: 
Series.to_frame(name=None)

#### Q. How to plot 3D plots using matplotlib?
Yes Function: import numpy as np import matplotlib.pyplot as plt fig = plt.figure() ax = plt.axes(projection ='3d')

In [ ]:
#Synatx:
import numpy as np 
import matplotlib.pyplot as plt 
fig = plt.figure() 
ax = plt.axes(projection ='3d')

#### Q.  How to convert categorical columns into a numeric column?
One of the most used and popular ones are LabelEncoder and OneHotEncoder. Both are provided as parts of sklearn library. LabelEncoder can be used to transform categorical data into integers: 

In [14]:
from sklearn.preprocessing import LabelEncoder 
label_encoder = LabelEncoder() 
x = ['Apple', 'Orange', 'Apple', 'Pear'] 
y = label_encoder.fit_transform(x) 
print(y)

[0 1 0 2]


In [15]:
#OneHotEncoder can be used to transform categorical data into one hot encoded array:

from sklearn.preprocessing import OneHotEncoder 
onehot_encoder = OneHotEncoder(sparse=False) 
y = y.reshape(len(y), 1) 
onehot_encoded = onehot_encoder.fit_transform(y) 
print(onehot_encoded)

[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


#### Q. How to remove duplicate data from a dataframe?
The 'drop_duplicates( )' function in python eliminates the redundant rows from the DataFrame and returns it.

In [ ]:
#Syntax: 
DataFrame.drop_duplicates(subset=None, keep=' ', inplace=False)

1. subset: Subset takes a column or list of column label. The default value is none. After passing columns, it will consider them only for duplicates. 
2. keep: keep is to control how to consider duplicate value. It has only three distinct values ('first', 'last', 'false')
3. default is 'first'.

#### Q. How do you select a sample of dataframe?
Depending on the situation, there are a few possible ways to select a sample from the dataframe - 
1. Randomly select a single row: df = df.sample() 
2. Randomly select a specified n number of rows: df = df.sample(n=3) 
3. Allow a random selection of the same row more than once: df = df.sample(n=3,replace=True) 
4. Randomly select a specified fraction of the total number of rows: df = df.sample(frac=0.50)

In [ ]:
#1. Randomly select a single row: 
df = df.sample()

#2. Randomly select a specified n number of rows: 
df = df.sample(n=3)

#3. Allow a random selection of the same row more than once: 
df = df.sample(n=3,replace=True)

#4. Randomly select a specified fraction of the total number of rows: 
df = df.sample(frac=0.50)

#### Q. How to use and Why to use "GroupBy" fuvntion in python?

Pandas dataframe.groupby() function is used to split the data into groups based on some criteria. pandas objects can be split on any of their axes.

In [ ]:
#Syntax: 
DataFrame.groupby(by=None, axis=0, level=None, as_index=True, sort=True, group_keys=True, squeeze=False, **kwargs)

1. by: mapping, function, str, or iterable 
2. axis: int, default 0 
3. level: If the axis is a MultiIndex (hierarchical), group by a particular level or levels 
4. as_index: For aggregated output, return object with group labels as the index. Only relevant for DataFrame input. 
5. sort: Sort group keys. Get better performance by turning this off. Note this does not influence the order of observations within each group. 
6. groupby preserves the order of rows within each group. group_keys: When calling apply, add group keys to index to identify pieces 
7. squeeze: Reduce the dimensionality of the return type if possible, otherwise return a consistent type 
8. Returns: GroupBy object

#### Q. How to check the distribution of data in python?
A simple and commonly used plot to quickly check the distribution of a sample of data is the histogram.

In [ ]:
from matplotlib import pyplot 
pyplot.hist(data)

#### Q. Important libraries in SciPy that you might need to work with during your project?
* SciPy contains modules for optimization, linear algebra, integration, interpolation, special functions, FFT, signal and image processing, ODE solvers etc 
* Subpackages include: scipy.cluster, scipy.constants, scipy.fftpack, scipy.integrate, scipy.interpolation, scipy.linalg, scipy.io, scipy.ndimage, scipy.odr, scipy.optimize, scipy.signal, scipy.sparse, scipy.spatial, scipy.special, scipy.stats, scipy.weaves